# Generated by Django 5.1.4 on 2024-12-10 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('0+', '0+'), ('0-', '0-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Boy (cm)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_end',
            field=models.DateField(blank=True, help_text='Üyelik bitiş tarihi', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_start',
            field=models.DateField(default=datetime.date.today, help_text='Üyelik başlangıç tarihi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kilo (kg)', max_digits=5, null=True),
        ),
    ]
