# Generated by Django 5.1.4 on 2024-12-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_managers_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Kullanıcı telefon numarası', max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(help_text='Kullanıcı soyadı', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Kullanıcı adı', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Kullanıcı şifresi', max_length=128),
        ),
    ]
