# Generated by Django 5.1.4 on 2024-12-11 01:04

import api.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_phone_number_user_surname_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='meals',
            field=models.ManyToManyField(help_text='Birden fazla seçmek için CTRL tuşuna basılı tutun.', to='api.meal'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='reps',
            field=models.IntegerField(default=12, help_text='Tekrar sayısı', validators=[api.models.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='movement',
            name='sets',
            field=models.IntegerField(default=3, help_text='Set sayısı', validators=[api.models.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='program',
            name='movements',
            field=models.ManyToManyField(help_text='Birden fazla seçmek için CTRL tuşuna basılı tutun.', to='api.movement'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_end',
            field=models.DateField(help_text='Üyelik bitiş tarihi', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+900000000000', help_text='Kullanıcı telefon numarası', max_length=128, region=None),
        ),
    ]
