# Generated by Django 5.1.4 on 2024-12-11 01:31

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_diet_meals_alter_movement_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+900000000000', help_text='Kullanıcı telefon numarası', max_length=128, null=True, region=None),
        ),
    ]
